[build] Add a NOCOMMIT pre-commit hook so things don't accidentally get committed

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -18,4 +18,9 @@ fi
 # If there are whitespace errors, print the offending file names and fail.
 git diff-index --check --cached $against --
 
+if [[ $(git diff --cached | grep NOCOMMIT) ]]; then
+  echo 'Error: NOCOMMIT present.';
+  exit 1;
+fi
+
 yarn run -s check
